name: Housekeeping

on:
  release:

jobs:
  updateshorttag:
    runs-on: ubuntu-latest

    steps:
    - name: Update the short tag to match the release tag
      run: echo "{{ github.event_name }} {{ github.event.action }}"
