# Perform general housekeeping tasks for this repo.

name: Housekeeping

on:
  release:

# A workflow run is made up of 1+ jobs that can run sequentially or in parallel
# Steps represent a sequence of tasks that will be executed as part of a job

jobs:
  bumptag:
    runs-on: ubuntu-latest

    steps:
    - name: Run a multi-line script
      run: |
        echo "{{ github.event_name }} {{ github.event.action }}"
        echo "{{ github.event.tag_name }}"
